### ISSUE TITLE
Bot display info in wrong situation

### ISSUE THREAD

**Issue by SG5** [mguellsegarra/diceroll_telegram_bot#1]
Bot shows a info message when you send any message, contains `/info`
For example: `https://github.com/info/`

**Comment by mguellsegarra** [comment]
Hi! Thanks for reporting this bug!

Turns out that I missed a `^` character in the regexp expressions to catch the commands.

It's now fixed, you can see the changes [here](https://github.com/mguellsegarra/diceroll_telegram_bot/commit/3b6c6e872da4812e8640e6e4da868ab6002adcf4)

Salut! :)
